import { CredentialError } from "./errors";
import { CREDENTIAL_ACQUISITION_PROTOCOL, CREDENTIAL_FORMAT, HOLDER_BINDING_DOMAIN, type CredentialFlowDescriptor } from "./types";

const ID = /^[a-z0-9][a-z0-9._-]{0,127}(?:\/v1)?$/;
const STEP_TYPES = new Set(["collect_input", "mailbox_otp", "holder_signature"]);
const ENDPOINTS = {
  request: "request", state: "state", challenge: "challenge", proof: "proof",
  holderBinding: "holder_binding", holderSignature: "holder_signature", issue: "issue", result: "result",
} as const;
const STATES = ["collecting", "challenging", "proving", "signing", "issuing", "verifying", "saving", "success", "recovery"] as const;

function fail(message: string): never { throw new CredentialError("DESCRIPTOR_INVALID", message); }
function unsupported(message: string): never { throw new CredentialError("UNSUPPORTED_PROFILE", message); }
function object(value: unknown, label: string): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) fail(`${label} must be an object`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, fields: readonly string[], label: string): void { const a = Object.keys(value).sort(); const b = [...fields].sort(); if (a.length !== b.length || a.some((key, index) => key !== b[index])) fail(`${label} has unknown or missing fields`); }
function text(value: unknown, label: string, pattern?: RegExp): string { if (typeof value !== "string" || value.length === 0 || value.length > 512 || (pattern && !pattern.test(value))) fail(`${label} is invalid`); return value; }
function integer(value: unknown, label: string, max = 31_536_000): number { if (!Number.isSafeInteger(value) || (value as number) < 1 || (value as number) > max) fail(`${label} is invalid`); return value as number; }
function origin(value: unknown): string { const candidate = text(value, "issuer.origin"); let url: URL; try { url = new URL(candidate); } catch { fail("issuer.origin is invalid"); } if (url!.protocol !== "https:" || url!.origin !== candidate || url!.username || url!.password) fail("issuer.origin is invalid"); return candidate; }

/** Strictly validates and preserves the Rust-owned canonical descriptor bytes. */
export function validateCredentialFlowDescriptor(value: unknown): CredentialFlowDescriptor {
  const raw = object(value, "descriptor");
  exact(raw, ["type", "contractVersion", "protocol", "profile", "profileVersion", "display", "accessibility", "theme", "issuer", "format", "claims", "subjectRelationship", "inputs", "steps", "holderBinding", "endpoints", "lifecycle", "status", "revocation", "presentation"], "descriptor");
  if (raw.type !== "tinycloud.credentials/descriptor/v1" || raw.contractVersion !== 1 || raw.protocol !== CREDENTIAL_ACQUISITION_PROTOCOL || raw.profileVersion !== 1) unsupported("Credential protocol or profile version is unsupported");
  text(raw.profile, "profile", ID);
  const display = object(raw.display, "display"); exact(display, ["title", "description", "consent", "securityTextLocked"], "display"); if (display.securityTextLocked !== true) fail("security text must be locked"); for (const key of ["title", "description", "consent"]) text(display[key], `display.${key}`);
  const accessibility = object(raw.accessibility, "accessibility"); exact(accessibility, ["progressLabel", "errorLiveRegion"], "accessibility"); text(accessibility.progressLabel, "accessibility.progressLabel"); if (accessibility.errorLiveRegion !== "assertive") fail("accessibility live region is invalid");
  const theme = object(raw.theme, "theme"); exact(theme, ["tokenVersion", "allowed"], "theme"); if (theme.tokenVersion !== "tinycloud.credentials/tokens/v1" || !Array.isArray(theme.allowed) || theme.allowed.join("\0") !== "accentColor\0fontFamily\0borderRadius") unsupported("Theme token version is unsupported");
  const issuer = object(raw.issuer, "issuer"); exact(issuer, ["did", "origin", "kid"], "issuer"); origin(issuer.origin); const did = text(issuer.did, "issuer.did", /^did:[a-z0-9]+:.+$/); const kid = text(issuer.kid, "issuer.kid"); if (!kid.startsWith(`${did}#`)) fail("issuer.kid is invalid");
  const format = object(raw.format, "format"); exact(format, ["id", "vct"], "format"); if (format.id !== CREDENTIAL_FORMAT) unsupported("Credential format is unsupported"); text(format.vct, "format.vct", ID);
  if (!Array.isArray(raw.claims) || raw.claims.length === 0 || raw.claims.length > 64) fail("claims are invalid"); const claimNames = new Set<string>(); for (const value of raw.claims) { const claim = object(value, "claim"); exact(claim, ["name", "matching", "selectiveDisclosure"], "claim"); const name = text(claim.name, "claim.name", ID); if (claimNames.has(name) || claim.matching !== "normalized_exact" || typeof claim.selectiveDisclosure !== "boolean") fail("claim is invalid"); claimNames.add(name); }
  if (raw.subjectRelationship !== "holder_is_subject") unsupported("Subject relationship is unsupported");
  if (!Array.isArray(raw.inputs) || raw.inputs.length === 0 || raw.inputs.length > 64) fail("inputs are invalid"); const inputIds = new Set<string>(); for (const value of raw.inputs) { const input = object(value, "input"); exact(input, ["id", "label", "schema", "prefill", "autocomplete"], "input"); const id = text(input.id, "input.id", ID); if (inputIds.has(id)) fail("input ids must be unique"); inputIds.add(id); text(input.label, "input.label"); if (input.prefill !== "privacy_hint_only" || input.autocomplete !== "off") fail("input privacy metadata is invalid"); const schema = object(input.schema, "input.schema"); if (Object.keys(schema).some((key) => !["type", "minLength", "maxLength", "pattern", "format"].includes(key)) || schema.type !== "string") unsupported("Input schema is unsupported"); if (schema.minLength !== undefined) integer(schema.minLength, "input.schema.minLength", 4096); if (schema.maxLength !== undefined) integer(schema.maxLength, "input.schema.maxLength", 4096); if (schema.pattern !== undefined) { const pattern = text(schema.pattern, "input.schema.pattern"); try { new RegExp(pattern, "u"); } catch { fail("input.schema.pattern is invalid"); } } if (schema.format !== undefined && schema.format !== "email") unsupported("Input format is unsupported"); }
  if (!Array.isArray(raw.steps) || raw.steps.length < 2 || raw.steps.length > 32) fail("steps are invalid"); for (const value of raw.steps) { const step = object(value, "step"); exact(step, ["type", "version"], "step"); if (!STEP_TYPES.has(step.type as string) || step.version !== 1) unsupported("Credential step type or version is unsupported"); } if (!(raw.steps as Record<string, unknown>[]).some((step) => step.type === "holder_signature")) fail("holder_signature is required");
  const binding = object(raw.holderBinding, "holderBinding"); exact(binding, ["required", "alg", "domain", "version"], "holderBinding"); if (binding.required !== true || binding.alg !== "EdDSA" || binding.domain !== HOLDER_BINDING_DOMAIN || binding.version !== 1) unsupported("Holder binding is unsupported");
  const endpoints = object(raw.endpoints, "endpoints"); exact(endpoints, Object.keys(ENDPOINTS), "endpoints"); for (const [name, id] of Object.entries(ENDPOINTS)) if (endpoints[name] !== id) fail("endpoint identifiers must use the registered vocabulary");
  const lifecycle = object(raw.lifecycle, "lifecycle"); exact(lifecycle, ["requestTtlSeconds", "challengeTtlSeconds", "maxProofAttempts", "challengeConsumption", "retry"], "lifecycle"); integer(lifecycle.requestTtlSeconds, "requestTtlSeconds"); integer(lifecycle.challengeTtlSeconds, "challengeTtlSeconds"); integer(lifecycle.maxProofAttempts, "maxProofAttempts", 100); if (lifecycle.challengeConsumption !== "atomic_once" || lifecycle.retry !== "bounded") fail("lifecycle semantics are invalid");
  const status = object(raw.status, "status"); exact(status, ["type", "freshnessSeconds"], "status"); if (status.type !== "none") unsupported("Credential status method is unsupported"); integer(status.freshnessSeconds, "status.freshnessSeconds");
  const revocation = object(raw.revocation, "revocation"); exact(revocation, ["supported"], "revocation"); if (revocation.supported !== false) unsupported("Credential revocation method is unsupported");
  const presentation = object(raw.presentation, "presentation"); exact(presentation, ["stateVersion", "states"], "presentation"); if (presentation.stateVersion !== "tinycloud.credentials/ux-states/v1" || !Array.isArray(presentation.states) || presentation.states.join("\0") !== STATES.join("\0")) unsupported("Presentation state version is unsupported");
  return Object.freeze(raw as unknown as CredentialFlowDescriptor);
}

export function credentialEndpointPath(id: "request" | "state" | "challenge" | "proof" | "holder_binding" | "holder_signature" | "issue" | "result" | "issuer_metadata" | "interaction", requestId?: string): string {
  const encoded = requestId === undefined ? "" : `/${encodeURIComponent(requestId)}`;
  return ({ request: "/v1/acquisitions", state: `/v1/acquisitions${encoded}/state`, challenge: `/v1/acquisitions${encoded}/challenge`, proof: `/v1/acquisitions${encoded}/proof`, holder_binding: `/v1/acquisitions${encoded}/holder-binding`, holder_signature: `/v1/acquisitions${encoded}/holder-signature`, issue: `/v1/acquisitions${encoded}/issue`, result: `/v1/acquisitions${encoded}/result`, issuer_metadata: "/.well-known/opencredentials/issuer", interaction: `/credential-acquisition${encoded}` } as const)[id];
}
