/**
 * Delegation management types for TinyCloud SDK v2.
 *
 * These types support the delegation, capability key management,
 * and sharing link functionality.
 *
 * All types are defined using Zod schemas in types.schema.ts and
 * re-exported here for backwards compatibility.
 *
 * @packageDocumentation
 */

// Re-export all types and schemas from the Zod schema file
export {
  createResultSchema,
  type Result,
  JWKSchema,
  type JWK,
  KeyTypeSchema,
  type KeyType,
  KeyInfoSchema,
  type KeyInfo,
  CapabilityEntrySchema,
  type CapabilityEntry,
  DelegationErrorSchema,
  type DelegationError,
  DelegationErrorCodes,
  type DelegationErrorCode,
  DelegationSchema,
  type Delegation,
  DelegationStatusSchema,
  type DelegationStatus,
  DelegationRevocationReceiptSchema,
  type DelegationRevocationReceipt,
  AccountDelegationResourceSchema,
  type AccountDelegationResource,
  AccountDelegationRecordSchema,
  type AccountDelegationRecord,
  AccountDelegationPageSchema,
  type AccountDelegationPage,
  AccountDelegationQueryOptionsSchema,
  type AccountDelegationQueryOptions,
  DelegationRecordSchema,
  type DelegationRecord,
  CreateDelegationParamsSchema,
  type CreateDelegationParams,
  DelegationChainSchema,
  type DelegationChain,
  DelegationChainV2Schema,
  type DelegationChainV2,
  DelegationDirectionSchema,
  type DelegationDirection,
  DelegationFiltersSchema,
  type DelegationFilters,
  SpaceOwnershipSchema,
  type SpaceOwnership,
  SpaceInfoSchema,
  type SpaceInfo,
  ShareSchemaSchema,
  type ShareSchema,
  ShareLinkSchema,
  type ShareLink,
  createShareLinkDataSchema,
  ShareLinkDataSchema,
  type ShareLinkData,
  IngestOptionsSchema,
  type IngestOptions,
  GenerateShareParamsSchema,
  type GenerateShareParams,
  DelegationManagerConfigSchema,
  type DelegationManagerConfig,
  KeyProviderSchema,
  type KeyProvider,
  DelegationApiResponseSchema,
  type DelegationApiResponse,
  CreateDelegationWasmParamsSchema,
  type CreateDelegationWasmParams,
  CreateDelegationWasmResultSchema,
  type CreateDelegationWasmResult,
  DelegatedResourceSchema,
  type DelegatedResource,
  validateDelegation,
  validateCreateDelegationParams,
  validateDelegationFilters,
  validateShareLink,
  createValidator,
} from "./types.schema.js";
