export { DEFAULT_MAX_CONTENT_BLOB_BYTES, DEFAULT_MAX_SEALED_BLOB_BYTES, SHARE_RESULT_VERSION, inspectShare, receiveShare, ShareReceiveError, toShareErrorInfo, verifyBearerEnvelope, type ShareErrorCode, type ShareErrorInfo, type ShareFetchOptions, type ShareInspection, type ShareMetadata, type ShareReceiveResult, type VerifyBearerEnvelopeOptions } from "./receive.js";
export { DEFAULT_SHARE_LIFETIME_MS, SHARE_CONTENT_LIMIT, SHARE_PUBLISH_RESULT_VERSION, SHARE_SEALED_OVERHEAD, publishShare, SharePublishError, type PublishedShare, type PublishedShareMetadata, type SharePublishErrorCode, type SharePublishOptions, type SharePublishTarget, type ShareUpload, type ShareUploadAuthorization, type ShareUploadInput, type ShareUploadResult } from "./publish.js";
export { parseAddressedEnvelope, type ParsedAddressedEnvelope } from "./addressed.js";
export { checkBearerDelegation, resourceUriCovers, requiredResourceUri, type CheckBearerDelegationOptions, type DelegationCheckResult } from "@tinycloud/share-envelope";
export { MemoryShareCache } from "./cache.js";
export type { ShareCache, ShareCacheEntry, ShareCacheKey, ShareCacheMetadata } from "./cache.js";
export { createDelegatedShareKey, restoreDelegatedShareKey, createPolicyEnforcementDelegation, canonicalOwnerSharePolicy, computeOwnerShareRegistrationCid, validateOwnerSharePolicyRegistration, validateOwnerSharePolicyRegistrationBytes, MAX_CONTENT_BYTES } from "./owner-policy.js";
export type { OwnerDelegationReceipt, CreateOwnerDelegationParams, OwnerShareAction, OwnerShareMatcher, OwnerSharePolicyV2, DelegatedShareKey, SignedDelegation, RegisterOwnerSharePolicyParams, OwnerSharePolicyRegistration, OwnerSharePolicyRegistrationReceipt } from "./owner-policy.js";
export { SHARE_DELIVERY_AUTHORIZATION_DOMAIN, validateShareDeliveryAuthorizationBytes, shareDeliveryTrustedKid } from "./delivery.js";
export type { ShareDeliveryAuthorizationRequest, ShareDeliveryAuthorization, ShareDeliveryAuthorizationReceipt, ValidateShareDeliveryAuthorizationExpected } from "./delivery.js";
export { MemorySenderShareRecordStorage, MemorySenderShareKeyStorage, SenderShareStore } from "./history.js";
export { MemoryEncryptedShareHistoryStorage, EncryptedSenderShareHistory } from "./history.js";
export type { SenderShareRecord, SenderShareRecordStorage, SenderShareKeyStorage, SenderShareRevocationScope, EncryptedShareHistoryStorage } from "./history.js";
export { authorizeShare, authorizationMethodForTarget } from "./authorization.js";
export type { ShareAuthorizationMethod, ShareAuthorizationRequired, ShareAuthorizationDenied, ShareAuthorizationReady, ShareAuthorizationResult, ShareAuthorizationAdapter } from "./authorization.js";
export { notifyShare, ShareNotifyError } from "./notify.js";
export type { ShareNotifyState, ShareNotifyResult, ShareNotifyInput, ShareDeliveryAdapter } from "./notify.js";
export { listShares, showShare, revokeShare } from "./lifecycle.js";
export type { ShareHistoryView, ShareRevocationResult, ShareRevocationAdapter } from "./lifecycle.js";
export { isLegacyShareLink, receiveLegacyShare, migrateShare } from "./legacy.js";
export type { LegacyShareReader, LegacyMigrationResult } from "./legacy.js";
export { normalizeShareTarget, publishTargetShare, targetAuthorizationMethod } from "./targets.js";
export type { ShareTarget, TargetPublishInput, TargetPublishOutcome, TargetPublishAdapter } from "./targets.js";
export { publishPolicyShare, claimShare, resumeShareAuthorization } from "./policy.js";
export type { SharePolicyPublishAdapter } from "./policy.js";
