export {
  SignatureMaterialError,
  SignatureVerificationError,
  SignedObjectCanonicalizationError,
  SignedObjectDigestError,
  SignedObjectIdError,
  SignedObjectProfileError,
  SignedObjectSchemaError,
  SigningKeyBindingError,
  UnsupportedSignatureSuiteError,
  toSignedObjectError,
  type SignedObjectErrorCode,
} from "./errors";

export {
  jcsCanonicalize,
  normalizeJson,
  serialize as serializeJcsJson,
  type JsonValue,
} from "./jcs";

export {
  ED25519_JCS_SIGNATURE_SUITE,
  EIP191_JCS_SIGNATURE_SUITE,
  POLICY_ENGINE_RECORD_SCHEMA,
  POLICY_SCHEMA,
  POLICY_STATUS_SCHEMA,
  canonicalizeSignedObjectUnsigned,
  createAndSignPolicy,
  createAndSignPolicyEngineRecord,
  createAndSignPolicyStatus,
  createAndSignSignedObject,
  deriveSignedObjectMaterial,
  signedObjectIdFor,
  validatePolicyEngineRecordSigned,
  validatePolicyEngineRecordSignedShape,
  validatePolicyEngineRecordUnsigned,
  validatePolicySigned,
  validatePolicySignedShape,
  validatePolicyStatusSigned,
  validatePolicyStatusSignedShape,
  validatePolicyStatusUnsigned,
  validatePolicyUnsigned,
  verifyPolicy,
  verifyPolicyEngineRecord,
  verifyPolicyStatus,
  verifySignedObject,
  type JsonObject,
  type Policy,
  type PolicyEngineRecord,
  type PolicyStatus,
  type SignatureSuite,
  type SignedObjectKind,
  type SignedObjectMaterial,
  type SignedObjectSignature,
  type SignedObjectSigner,
  type SignedObjectVerificationResult,
  type SignedPolicyObject,
  type UnsignedPolicy,
  type UnsignedPolicyEngineRecord,
  type UnsignedPolicyObject,
  type UnsignedPolicyStatus,
} from "./signed-object";
